config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :feedbacks

  # instead of default users/sign_up it will be auth/sign_up. 
  #map the routes from the default registration controller to our own registration controller.
  devise_for :users, path: 'auth'
  # map the base /auth path to the new registration action. This is incase the user submits wrong form then goes back to /auth and accidentally refreshes. Then they just hav this form again
  devise_scope :user do
    get 'auth', to: 'users/sessions#new'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }  
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  
  attribute :category, :string, default: "Feature"

  belongs_to :user

  def belongs_to_user?(user)
    id == user.id
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :username, presence: true, 
         uniqueness: { case_sensitive: false}, 
         length: {minimum: 3, maximum: 25}

  validates :full_name, presence: true

  has_many :feedbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  # before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :full_name])
  end

  protected
  
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :alert => 'You need to login to create a feedback!'
    end
  end

  def after_sign_in_path_for(user)
    puts "thing that signed in: #{user}"
    stored_location_for(user) || super
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :feedback_categories, only: [:new, :create]

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = current_user.feedbacks.build(feedback_params)

    if @feedback.save
      redirect_to @feedback
    else
      render :new
    end

  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  private

  def feedback_params
    params.require(:feedback).permit(:title, :description, :category)
  end

  def feedback_categories
    @categories = ["Feature", "UI", "UX", "Enhancement", "Bug"]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @feedbacks = Feedback.all()
    @categories = ["Feature", "UI", "UX", "Enhancement", "Bug"]
    @filters = ["Most Upvotes", "Least Upvotes", "Most Comments", "Least Comments"]
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @signup = 'active'
    super
  end

  # POST /resource
  def create
    @signup = 'active'
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    # self.resource = resource_class.new(sign_in_params)
    # clean_up_passwords(resource)
    # yield resource if block_given?
    # respond_with(resource, serialize_options(resource))
    @login = 'active'
    super
  end


  # POST /resource/sign_in
  def create
    @login = 'active'
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected


end

app/helpers/application_helper.rb
module ApplicationHelper
  def extends(layout, &block)
    # Make sure it's a string
    layout = layout.to_s

    # If there's no directory component, presume a plain layout name
    layout = "layouts/#{layout}" unless layout.include?('/')

    # Capture the content to be placed inside the extended layout
    @view_flow.get(:layout).replace capture(&block)

    render template: layout
  end


  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name].join(", ")
      end
    end
  end 

  def is_signup_page?(controller)
    controller_name == controller
  end

  def is_editable?(feedback)
     action_name == "show" && feedback.belongs_to_user?(current_user)
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/feedbacks/_feedback.html.erb
<div class="feedback">

  <%= link_to feedback_path(feedback), class:"feedback-content" do %>
    <%= image_tag("default.jpg", class: "profile-img", id: "profile-img") %>
    
    <p class="feedback-info">
      <strong class="name"><%= feedback.user.full_name %></strong>
      <br>
      <%= feedback.created_at.strftime("%Y-%m-%d") %>
    </p>

    <p class="body">
      <strong>
        <%= feedback.title %>
      </strong>
      <br>
      <%= feedback.description %>
    </p>

    <p class="filled-box cate"><%= feedback.category %></p>
  <% end %>




  <%= button_to root_path, class: "filled-box like" do %>
    <svg width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 6l4-4 4 4" stroke="#4661E6" stroke-width="2" fill="none" fill-rule="evenodd"/></svg><strong>0</strong>
  <% end %>

  <strong class="comment">12</strong>
</div>

app/views/feedbacks/new.html.erb
  <%# the form %>
  <div class="form-wrapper">
    <%= form_with(model: @feedback, local: true, id: "feedback-form", class: "feedback-form") do |f|%>
      <%# plus icon %>
      <div aria-hidden="true" class="feedback-form-icon">
        <svg width="1em" height="1em" viewBox="0 0 12 12" fill="none" class="text-white mobile:text-small"><path d="M7.673 11.714V7.547h4.062V4.474H7.673V.286H4.39v4.188H.286v3.073H4.39v4.167h3.283z" fill="white"></path></svg>
      </div>
      
      <h1>Create New Feedback</h1>

      <div class="form-group title">
        <%= f.label :title, 'Feedback Title' %>
        <p class="desc">Add a short, descriptive headline
        </p>

        <%= f.text_field :title, id: "title-input", value: @feedback.title, autofocus: true %>
      </div>
      

      
      <div class="form-group">
        <%= f.label :category %>
        <p class="desc">Choose a category for your feedback
        </p>
        <%= f.hidden_field :category, value: 'feature' %>

      </div>

      <div class="selection">
       
        <p id="category-toggle"  class="category-toggle selection-toggle">
          <%= @feedback.category ? @feedback.category : "Feature" %>
        </p>

        <ul id="category-options"  class="category-options selection-options">
          <% @categories.each do |category| %>
            <li>
              <button type="button" class="option category <%= 'selected' if @feedback.category == category %>"><%= category %></button>
            </li>
          <% end %>
        </ul>

      </div>
        
      <div class="form-group detail">
        <%= f.label :description, 'Feedback Detail' %>

        <p class="desc">Include any specific comments on what should be improved, added, etc.</p>

        <%= f.text_area :description, id: "desc-input", row: 8, value: @feedback.description %>
      </div>
      
      <div class="form-links">
        <%= f.submit class: "bordered-link purple" %>
        <%= link_to 'Cancel', root_path, class: "bordered-link dark-blue" %>
      </div>
    <% end %> 
  </div>

app/views/feedbacks/show.html.erb
<section class="show-feedback">
  <%= render @feedback %>
</section>

<section>
  <h3>Add Comment</h3>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductFeedbackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
        <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise_auth.html.erb
<%= extends :application do %>
  <section class="auth">
    <div class="auth-content">
      <%= render partial: 'shared/goback-nav', locals: {editable: false} %>
      
      <div class="profile-pic"></div>
      <div class="auth-links">
        <%= link_to 'Login', new_user_session_path, class: "#{'active' if is_signup_page?('sessions')}" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "#{'active' if is_signup_page?('registrations')}" %>
      </div>
      <%= yield %>
    </div>
  </section>
<% end %>

app/views/layouts/feedbacks_layout.html.erb
<%= extends :application do %>
  <div class="container crud-feedback-container">
    
    <%= render partial: 'shared/goback-nav', locals: {editable: is_editable?(@feedback) } %>

    <%= yield %>
  </div>
<% end %>

app/views/shared/_goback-nav.html.erb
<div class="go-back">
  <%= link_to 'javascript:history.back()', class: "go-back-nav" do %>
    <svg width="7" height="10" xmlns="http://www.w3.org/2000/svg"><path d="M6 9L2 5l4-4" stroke="#4661E6" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
    Go Back
  <% end %>

  <% if editable %>
    <%= link_to 'Edit Feedback', new_feedback_path, class: "bordered-link blue" %>
  <% end %>
</div>